# Site settings
title: npstr.space
description: npstr.space
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://npstr.space" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: npstr.space
#user_description:
#user_title:
email: napster@npstr.space
#twitter_username: lorem_ipsum
github_username:  napstr
#gplus_username:  lorem_ipsum
keybase_username: napster

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
