# Site settings
title: npstr.space
description: npstr.space
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://npstr.space" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: npstr.space
#user_description:
#user_title:
email: hello@npstr.space
twitter_username: _npstr
github_username:  napstr
#gplus_username:  lorem_ipsum
keybase_username: napster
patreon_username: napster
twitch_username: n_pster

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'package-lock.json', 'yarn.lock', 'gulpfile.js']
include: ['_headers']
